#! /usr/bin/env bash

original="$1"
other="$2"

function usage ()
{
	echo "Usage: check path/to/original/config.cfg [path/to/generated/config.ini]" 
	echo "Output the diff between two configuration files for airos"
	echo "By default diff /path/to/original/config.cfg and /path/to/original/config.ini"
}

function dothemagic ()
{
	default="$(dirname $original)/$(basename $original .cfg).ini"
	generated=${other:-$default}

	grep -v "#" "$original" | sort > "$original.sorted"
	grep -v "#" "$generated" | sort > "$generated.sorted"

	diff -d "$original.sorted" "$generated.sorted"

	rm {$original,$generated}.sorted
}

if [ -z $original ]; then
	usage
else
	dothemagic
fi
