#! /usr/bin/env bash
set -e -o pipefail

input="$1"

function usage ()
{
	echo "Usage: json path/to/config.json"
	echo "Pretty print the config.json merged with conf/nobrick.json"
}

function dothemagic ()
{
	netjsonconfig -c $input -t conf/nobrick.json -b airos -m json | json_pp
}
if [ -z $input ]; then
	usage
else
	dothemagic
fi
